export {default as OnboardingScreen} from './onboarding/OnboardingScreen'
export {default as HomeScreen} from './home/HomeScreen'
export {default as RegisterScreen} from './authentication/RegisterScreen'
export {default as LoginScreen} from './authentication/LoginScreen'
export {default as SearchScreen} from './search/SearchScreen'
export {default as AppointmentScreen} from './appointments/AppointmentsScreen'
export {default as ExploreScreen} from './explore/ExploreScreen'
export {default as ProfileScreen} from './profile/ProfileScreen'